ARG BASE_IMAGE=andycyx/ireconx:base
FROM ${BASE_IMAGE}

WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm install --include=dev --prefer-offline --no-audit

COPY . .

EXPOSE 3000

CMD ["sh", "-c", "npm run db:generate && npm run dev -- --hostname 0.0.0.0"]
